<?php

namespace AppBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{


    //function to return active addresses
    public function findActiveAddresses($userId){
        // echo $userId;
        // die;
        return $this->createQueryBuilder('a')
               
                    // ->setParameter('userType', self::SELLER)
                    ->andWhere('a.userId = :userId')
                    ->andWhere('a.status = :status')
                    ->setParameter('userId', $userId)
                    ->setParameter('status', 'active')
                    ->getQuery()
                    ->getResult();
    }
     
    
    //function to return deactive addresses
    public function findDeactiveAddresses($userId){
        return $this->createQueryBuilder('a')
                    // ->andWhere('a.userId = :userId')
                    // ->andwhere('a.status = :status')
                    // ->setParameter('userId', $userId)
                    // ->setParameter('status', 'deactive')
                    ->leftJoin('a.address','as')
                    // ->setParameter('userType', self::SELLER)
                    ->getQuery()
                    ->getResult();
    }

    public function setAddressActive($addressId){

        $dm = $this->getEntityManager();
        $address = self::find($addressId);
        $address->setStatus('active');
        $dm->flush();
        return;

    }
}
