<?php

namespace AppBundle\Repository;

/**
 * modelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllModel(){
        return $this->createQueryBuilder('m')
                    ->leftJoin('m.product', 'p')
                    ->getQuery()
                    ->getResult();
 
 
         // $entityManager = $this->getEntityManager();
        // $qr =  $entityManager->createQuery(
        //                 'SELECT p.name,m.name
        //                 FROM AppBundle\Entity\Model m
        //                 LEFT JOIN AppBundle\Entity\Product p
        //                 with m.product = p.id'
        //             );
                    // ->getQuery()
                    // ->getResult();
                //   return $qr->execute();
    }
}
