<?php

namespace AppBundle\Repository;

/**
 * SellerProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllProduct($sellerId){
        return $this->createQueryBuilder('sc')
        ->andWhere('sc.sellerId =:sellerId')
        ->setParameter('sellerId',$sellerId)
        ->getQuery()
        ->getResult();
    }
}
