<?php

namespace AppBundle\Repository;

/**
 * SpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationRepository extends \Doctrine\ORM\EntityRepository
{
    // public function findSpecfication($modelId) {
    //     return  $this->createQueryBuilder('s')
    //     ->getQuery() 
    //     // ->setParameter('userType', self::SELLER)
    //     // ->andWhere('s.model.id = :modelId')
    //     // ->setParameter('modelId', $modelId)
    //     // ->setHint(\Doctrine\ORM\Query::HINT_INCLUDE_META_COLUMNS, true)

    //     // ->getQuery()
    //     ->getResult();
    //     // createQueryBuilder('p')
    //         //   ->getQuery()
    //         //   ->setHint(\Doctrine\ORM\Query::HINT_INCLUDE_META_COLUMNS, true)
    //         //   ->getArrayResult();
    // }
}
