<?php

namespace AppBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllSubCategory(){
        return $this->createQueryBuilder('sc')
        ->leftJoin('sc.category', 'c')
        ->getQuery()
        ->getResult();
    }
}
