<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    const SELLER = 1;
    const CUSTOMER =2;
    const ADMIN = 3;

    //function to return seller details

    public function findAllSeller(){
        return $this->createQueryBuilder('u')
                    ->andWhere('u.userType = :userType')
                    // ->setParameter('userType', 'seller')
                    ->setParameter('userType', self::SELLER)
                    ->getQuery()
                    ->getResult();
    }

       //function to return seller details

       public function findAllCustomer(){
        return $this->createQueryBuilder('u')
                    ->andWhere('u.userType = :userType')
                    // ->setParameter('userType', 'customer')
                    ->setParameter('userType', self::CUSTOMER)
                    ->getQuery()
                    ->getResult();
    }
}
